name: Solar System Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  REPO_OWNER: rydergreystorm
jobs:
  unit-testing:
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_systems: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_systems: macos-latest
          - nodejs_version: 19
            operating_systems: macos-latest
          - nodejs_version: 20
            operating_systems: macos-latest
    runs-on: ${{ matrix.operating_systems }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs_version }}
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests for NodeJS version ${{ matrix.nodejs_version }} on ${{ matrix.operating_systems }}
        run: |
          npm run test
          ls -a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results-${{ matrix.nodejs_version }}-${{ matrix.operating_systems }}
          path: test-results.xml

  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        run: npm run coverage

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Report
          path: coverage
          retention: 5
        
  docker:
    name: Containerization
    permissions:
      packages: write
    needs: [code-coverage, unit-testing]
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        id: check_login
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Building for Testing
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Running Test
        run: |
          docker images
          docker run --name solar-system-app -d \
          -p 3000:3000 \
          -e MONGO_URI=$MONGO_URI \
          -e MONGO_USERNAME=$MONGO_USERNAME \
          -e MONGO_PASSWORD=$MONGO_PASSWORD \
          ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          echo "Testing Image URL using wget"
          wget -q -O - 127.0.0.1:3000/live | grep -i live

      - name: Push to Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: false
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.run_number }}
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:latest
            ghcr/${{ env.REPO_OWNER }}/solar-system:${{  github.run_number }}
            ghcr/${{ env.REPO_OWNER  }}/solar-system:$latest





