name: Solar System Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-testing:
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_systems: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_systems: macos-latest
          - nodejs_version: 19
            operating_systems: macos-latest
    runs-on: ${{ matrix.operating_systems }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs_version }}
      
      - name: Cache Dependencies
        uses: actions/cache@4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests for NodeJS version ${{ matrix.nodejs_version }} on ${{ matrix.operating_systems }}
        run: |
          npm run test
          ls -a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results-${{ matrix.nodejs_version }}-${{ matrix.operating_systems }}
          path: test-results.xml

  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        run: npm run coverage

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Report
          path: coverage
          retention: 5




