name: Solar System Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  unit-testing:
    services:
      mongodb-svc:
        image: siddharth67/mongo-db:non-prod
        ports:
          - 27017:27017
    env:
      MONGO_URI: 'mongodb://localhost:27017/superData'
      MONGO_USERNAME: ${{ vars.MONGO_TEST_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_TEST_PASSWORD }}

    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_systems: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs_version: 18
            operating_systems: macos-latest
          - nodejs_version: 19
            operating_systems: macos-latest
          - nodejs_version: 20
            operating_systems: macos-latest
    runs-on: ${{ matrix.operating_systems }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs_version }}
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}

      - name: Install Dependencies
        run: npm install 

      - name: Run Unit Tests for NodeJS version ${{ matrix.nodejs_version }} on ${{ matrix.operating_systems }}
        run: |
          npm run test
          ls -a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results-${{ matrix.nodejs_version }}-${{ matrix.operating_systems }}
          path: test-results.xml

  code-coverage:
    runs-on: ubuntu-latest
    container:
      image: node:20
    services:
      mongodb:
        image: siddharth67/mongo-db:non-prod
        options:
          --name mongo
    env:
      MONGO_URI: 'mongodb://mongo:27017/superData'
      MONGO_USERNAME: ${{ vars.MONGO_TEST_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_TEST_PASSWORD }}
        

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        run: npm run coverage

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Report
          path: coverage
          retention: 5
        
  docker:
    name: Containerization
    permissions:
      packages: write
    needs: [code-coverage, unit-testing]
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        id: check_login
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Building for Testing
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Running Test
        run: |
          docker images
          docker run --name solar-system-app -d \
          -p 3000:3000 \
          -e MONGO_URI=$MONGO_URI \
          -e MONGO_USERNAME=$MONGO_USERNAME \
          -e MONGO_PASSWORD=$MONGO_PASSWORD \
          ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          echo "Testing Image URL using wget"
          wget -q -O - 127.0.0.1:3000/live | grep -i live

      - name: Push to Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: false
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.run_number }}
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:latest
            ghcr.io/${{ env.REPO_OWNER }}/solar-system:${{  github.run_number }}
            ghcr.io/${{ env.REPO_OWNER  }}/solar-system:latest

  dev-deploy:
    if: contains(github.ref, 'features/')
    needs: docker
    uses: ./.github/workflows/reuse-workflow.yaml
    secrets:
      kube_secret: ${{ secrets.KUBECONFIG }}
    with:
      repo_owner: rydergreystorm #Could also be stored as a repo or org varaible and passed as $#{{ vars.REPO_OWNER }}
      environment: development
      k8s-manifest-dir: kubernetes/development/

  prod-deploy:
    if: github.ref == 'refs/head/main'
    needs: docker
    uses: ./.github/workflows/reuse-workflow.yaml
    secrets:
      kube_secret: ${{ secrets.KUBECONFIG }}
    with:
      repo_owner: rydergreystorm #Could also be stored as a repo or org varaible and passed as $#{{ vars.REPO_OWNER }}
      environment: production
      k8s-manifest-dir: kubernetes/production/

  publish-reports:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [unit-testing, code-coverage]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Group artifacts
        run: |
          ls -ltr
          mkdir reports-${{ github.sha }}
          mv mocha-test-results-* "Code Coverage Report" reports-${{ github.sha }}/
          ls reports-${{ github.sha }}
        